<?php
require('template/header.phtml');
require('session_helper.php');

flash('register')
?>

    <html>
    <head>
        <meta charset="utf-8">
        <title>Sign-Up</title>
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css">
    </head>
    <body>
    <div class="login">
        <h1>Sign-Up</h1>
        <form action="/Users.php" method="post">
            <input type = "hidden" name="type" value="register" >
            <label for="First Name">
                <i class="fas fa-id-card"></i>
            </label>
            <input type="text" name="firstname" placeholder="Enter First Name" id="firstname" required>
            <label for="Last Name">
                <i class="fas fa-id-card"></i>
            </label>
            <input type="text" name="lastname" placeholder="Enter Last Name" id="lastname" required>
            <label for="username">
                <i class="fas fa-user"></i>
            </label>
            <input type="text" name="username" placeholder="Enter Username" id="username" required>
            <label for="password">
                <i class="fas fa-lock"></i>
            </label>
            <input type="password" name="password" placeholder="Enter Password" id="password" required>
            <label for="password">
                <i class="fas fa-lock"></i>
            </label>
            <input type="password" name="passwordrepeat" placeholder="Confirm Password" id="password" required>
            <input type="submit" value="Sign-Up">
        </form>
    </div>
    </body>
    </html>

<?php
require('template/footer.phtml') ?>