<?php
session_start()
?>

<link href="/css/my-style.css" rel="stylesheet" type="text/css">
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Find My Friends</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>
<div class="m-4">
    <nav class="navbar fixed-top navbar-expand-lg navbar-light" style="background-color: #ff5700;''>
        <div class="container-fluid">
            <a href="#" class="navbar-brand">FindMyFriends</a>
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <div class="navbar-nav">
                    <a href="/index.php" class="nav-item nav-link active m-2">Home</a>
                    <a href="/friendsList.php" class="nav-item nav-link m-2">All Users</a>
                    <a href="/AssessmentCriteria.pdf" class="nav-item nav-link m-2" tabindex="-1">AssessmentCriteria</a>
                </div>
                <?php if(!isset($_SESSION['id'])) : ?>


                    <div class="container-fluid justify-content-start">
                        <a href="/loginPage.php" <button class="btn float-end btn-outline-dark " type="button">Log In</button> </a>
                    </div>
                    <div class="container-fluid justify-content-start">
                        <a href="/signupPage.php" <button class="btn float-end btn-outline-dark" type="button">Sign-Up</button> </a>
                    </div>
                <?php else: ?>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <div class="navbar-nav">
                        <a href="/yourFriends.php" class="nav-item nav-link active m-2">Your Friends</a>
                    <div class="container-fluid justify-content-start">
                        <a href="/Users.php?q=logout" <button class="btn float-end btn-outline-dark" type="button">Log-Out</button> </a>
                    </div>
                <?php endif;; ?>
            </div>
        </div>
    </nav>
</div>
</body>
